'use client';

import { Inter,Roboto } from "next/font/google";
import "./globals.css";
import SideMenu from "@/components/SideMenu/SideMenu";
import Header from "@/components/Header/Header";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"] , weight: ["400", "700"]});

// export const metadata = {
//   title: "App Avaliação de Desempenho",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const routePath = usePathname();

  if(routePath === "/" || routePath === "/login"){
    return (
      <html lang="en">
        <body className={`${inter.className} flex justify-center items-center h-screen`}>
          {children}
        </body>
      </html>
    )
  }

  return (
    <html lang="en">
      <body className={`${inter.className} min-h-full max-w-screen`}>
        <div className="flex flex-row max-w-screen">
          <SideMenu/>
            <div className="flex flex-col h-full w-full bg-gray-200">
            <Header/>         
              <div className="flex flex-col gap-1  h-full w-full bg-gray-200 p-10">
                {children}
              </div>
            </div>
        </div>
      </body>
    </html>
  );
}
