'use strict';
import { Inter } from "next/font/google";
import "./globals.css";
import SideMenu from "@/components/SideMenu/SideMenu";
import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "App Avaliação de Desempenho",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-row min-h-screen max-w-screen`}>
      <SideMenu/>
        <div className="flex flex-col min-h-screen w-full bg-gray-200">
        <Header/>         
          <div className="flex flex-col gap-1 flex-grow min-h-screen w-full bg-gray-200 p-10">
            {children}
          </div>
        </div>
        
      </body>
    </html>
  );
}
